version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0
    working_directory: ~/project

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies (Force Peer Resolution)
          command: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Optional Build Step
          command: |
            if grep -q '"build":' package.json; then
              npm run build
            else
              echo "⚠️ No build script found. Skipping build step."
            fi

      - run:
          name: Deploy to Railway
          command: |
            npm install -g @railway/cli
            export RAILWAY_TOKEN=$RAILWAY_TOKEN
            railway up --service your-service-name

workflows:
  version: 2
  deploy-on-main:
    jobs:
      - build-and-deploy
