version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies (Force Peer Resolution)
          command: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Build Vite Project
          command: npm run build

      - run:
          name: Confirm Build Output
          command: ls -lh dist || echo "❌ No dist/ folder found"

workflows:
  version: 2
  vite-build-only:
    jobs:
      - build
