version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: |
            if [ -f package.json ] && grep -q '"test":' package.json; then
              npm test
            else
              echo "No test script found. Skipping tests."
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
