version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: npm ci || npm install --legacy-peer-deps
      - run:
          name: Run Tests
          command: npm test

workflows:
  build_and_test:
    jobs:
      - build
