version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0
    working_directory: ~/project

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Run Tests
          command: |
            if [ -f package.json ] && grep -q '"test":' package.json; then
              npm test
            else
              echo "No test script found. Skipping tests."
            fi

      - run:
          name: Deploy to Railway
          command: |
            npm install -g @railway/cli
            railway up
          environment:
            RAILWAY_TOKEN: $RAILWAY_TOKEN

workflows:
  version: 2
  deploy-on-main:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main
