version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.1.0
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies (force peer compatibility)
          command: npm install --legacy-peer-deps

      - save_cache:
          paths:
            - node_modules
          key: v1-deps-{{ checksum "package-lock.json" }}

      - run:
          name: Generate Prisma Client
          command: npx prisma generate

  deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install Railway CLI
          command: npm install -g @railway/cli

      - run:
          name: Deploy to Railway
          command: |
            export RAILWAY_TOKEN=$RAILWAY_TOKEN
            railway up

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
